SEARCH_DIR(/lib/)
SEARCH_DIR(/usr/lib/)
SEARCH_DIR(/usr/lib/x86_64-linux-gnu/)
SEARCH_DIR(./test/)
SEARCH_DIR(./bin/units/x86_64-freebsd/)
SEARCH_DIR(./bin/)
INPUT(
prt0.o
bin/units/x86_64-freebsd/test_serial.o
bin/units/x86_64-freebsd/system.o
bin/units/x86_64-freebsd/objpas.o
bin/units/x86_64-freebsd/serial.o
bin/units/x86_64-freebsd/baseunix.o
bin/units/x86_64-freebsd/termio.o
bin/units/x86_64-freebsd/unix.o
bin/units/x86_64-freebsd/unixtype.o
bin/units/x86_64-freebsd/sysctl.o
bin/units/x86_64-freebsd/syscall.o
bin/units/x86_64-freebsd/unixutil.o
)
